pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "output"

train_data:
  video_path: "no path"
  prompt: "None"
  n_sample_frames: 12
  width: 256
  height: 256
  sample_start_idx: 0
  sample_frame_rate: 4
  dataset_set: "train"

validation_data:
  prompts:
    - "A Iron man on the beach"
    - "A Spider man on the snow"
    - "A Superman on the street"
    - "A boy on the forest"
  video_length: 4
  width: 256
  height: 256
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50
  dataset_set: "val"


learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 200
checkpointing_steps: 1000
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"
  - "conv_temporal"
skeleton_path: './pose_example/vis_kun_pose2.mov'


seed: 33
mixed_precision: 'no'
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
